## If the whitelist is enabled
Enabled: true
## Message that shows when a player cannot join.
KickMessage: '&4&lYou are not whitelisted!'
## The list of whitelisted people.
Whitelist:
- LaxWasHere
- codename_B
- md_5